"""empty message

Revision ID: d457297ca9c4
Revises: 
Create Date: 2025-11-09 12:26:10.342936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd457297ca9c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nombre_categoria', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria'),
    sa.UniqueConstraint('nombre_categoria')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('correo_electronico', sa.String(length=150), nullable=False),
    sa.Column('contrasena', sa.String(length=255), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('genero', sa.String(length=20), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.Enum('ausente', 'en-linea', 'ocupado', name='estado_usuario'), nullable=False),
    sa.Column('acepta_terminos', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_table('habilidades',
    sa.Column('id_habilidad', sa.Integer(), nullable=False),
    sa.Column('nombre_habilidad', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id_categoria'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_habilidad')
    )
    op.create_table('mensajes',
    sa.Column('id_mensaje', sa.Integer(), nullable=False),
    sa.Column('id_emisor', sa.Integer(), nullable=False),
    sa.Column('id_receptor', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('visto', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_emisor'], ['usuarios.id_usuario'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_receptor'], ['usuarios.id_usuario'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_mensaje')
    )
    op.create_table('intercambios',
    sa.Column('id_intercambio', sa.Integer(), nullable=False),
    sa.Column('id_usuario_oferta', sa.Integer(), nullable=False),
    sa.Column('id_usuario_demanda', sa.Integer(), nullable=True),
    sa.Column('id_habilidad', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('intercambio_finalizado', sa.Boolean(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_habilidad'], ['habilidades.id_habilidad'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_usuario_demanda'], ['usuarios.id_usuario'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario_oferta'], ['usuarios.id_usuario'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_intercambio')
    )
    op.create_table('usuarios_habilidades',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_habilidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_habilidad'], ['habilidades.id_habilidad'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_usuario', 'id_habilidad')
    )
    op.create_table('puntuaciones',
    sa.Column('id_puntuacion', sa.Integer(), nullable=False),
    sa.Column('id_intercambio', sa.Integer(), nullable=False),
    sa.Column('id_puntuador', sa.Integer(), nullable=False),
    sa.Column('id_puntuado', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Float(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_intercambio'], ['intercambios.id_intercambio'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_puntuado'], ['usuarios.id_usuario'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_puntuador'], ['usuarios.id_usuario'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_puntuacion'),
    sa.UniqueConstraint('id_intercambio', 'id_puntuador', name='uq_intercambio_puntuador')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puntuaciones')
    op.drop_table('usuarios_habilidades')
    op.drop_table('intercambios')
    op.drop_table('mensajes')
    op.drop_table('habilidades')
    op.drop_table('usuarios')
    op.drop_table('categorias')
    # ### end Alembic commands ###
