### Obtener la lista de los Usuarios (GET)
GET http://localhost:5000/api/usuarios
Accept: application/json

###

### Obtener Usuario por ID (GET)
GET http://localhost:5000/api/usuarios/1
Accept: application/json

###

### Añadir un Usuario (POST)
POST http://localhost:5000/api/usuarios
Content-Type: application/json
Accept: application/json

{
    "nombre": "loquita",
    "apellido": "Ramirez",
    "correo_electronico": "diego.ramirez@example.com",
    "fecha_nacimiento": "1997-10-14",
    "contrasena": "123456789",
    "foto_perfil": "...",
    "genero": "masculino",
    "descripcion": "...",
    "estado": false,
}

###

### Actualizar datos de usuario (PUT)
PUT http://localhost:5000/api/usuarios/3
Content-Type: application/json
Accept: application/json

{
    "nombre": "marta",
    "apellido": "Ramirez",
    "correo_electronico": "molo.ramirez@example.com",
    "fecha_nacimiento": "1997-10-14",
    "contrasena": "123456789",
    "foto_perfil": "...",
    "genero": "masculino",
    "descripcion": "...",
    "estado": false
}

###

### Borrar/Eliminar un Usuario (DELETE)
DELETE http://localhost:5000/api/usuarios/2
Accept: application/json